analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#010101'
    - '#FEFEFE'
    - '#FBFBFB'
  brandStrength: 0.560688
  lightness: 0.220105
  rhythmicContrast: 0.080428
  saturation: 0.426969
cta: {}
layout_spectrum: 0.146396
name: lij
opengraph: {}
purpose: []
typography_spectrum: 0.692567
